### PR TITLE
Updates resolution selection when ARCore is opened to match supported…

### PR DESCRIPTION
**Pull request by Bercon**
… resolutions.

To avoid clutter and keep code simple the resolution list just gets replaced with whatever previous mode had.

More comprehensive solution would keep track of all supported resolutions for all modes and annotate them with "640x480 (arcore,arengine)" or something like that. Do you think that'd be more appropriate here?

### CODE REVIEW

**Comment by pekkaran** [comment]
I think this is okay. It mirrors the way you need to run once after installation to generate the resolution list for the Camera2 mode, and also the iOS app does the same with camera configurations. The FPS selection could be implemented like this too.

**Review by pekkaran — APPROVED** [review]
Works.

**Comment by Bercon** [comment]
Added FPS. It displays the values correctly, but at least the Camera2 API refused to abide by the settings. For ARCore my devices only support 30fps, so I can't test if 60fps mode works.

**Comment by oseiskar** [comment]
Does this still allow running the algorithm with low FPS such as 10 or 15? Are those typically included in the FPS list? If not, this could be handled by systematically dropping, e.g., every second frame in one of the higher-FPS modes. Lower-end phones may have difficulties with high FPS and also demonstrating performance with lower FPS is still relevant

**Comment by Bercon** [comment]
Well it should. However I'm not sure how well this is supported on different devices. On my phone despite having options for lower framerates, it always ran at 30fps regardless of the requested target FPS.

Based on the official documentation and stackoverflow answers, it should work. https://developer.android.com/reference/android/hardware/camera2/CaptureRequest#CONTROL_AE_TARGET_FPS_RANGE

I think we should have a separate switch to halve the actual framerate as well to support lower-end devices since this doesn't seem very reliable.

**Review by oseiskar — APPROVED** [review]

**Pull request merged**
